### ISSUE TITLE
neo4j-atag does not work on debian bullseye neo4j community installation

### ISSUE THREAD

**Issue by kuczera** [THM-Graphs/neo4j-atag#5]
Snippet from debug.og:

`2024-04-08 06:43:56.775+0000 WARN  [o.n.k.a.p.GlobalProcedures] Failed to load `atag.text.Importer` from plugin jar `/var/lib/neo4j/plugins/neo4j-atag-v0.2.4.jar`: java.lang.UnsupportedClassVersionError: atag/text/Importer has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
`

**Comment by sarmbruster** [comment]
Reason here is that the project uses currently JDK 21.
Neo4j >=5.0.14 runs on both JDK 17 and JDK 21. If an existing Neo4j instance uses JDK 17 the above error will happen.
I'll change the code so this project works with JDK 17 so no existing deployment will be broken.
